image: nativecode/deno:0.2.0

stages:
  - test
  - publish

test:
  stage: test
  script:
    - deno run --allow-net https://raw.githubusercontent.com/nativecode-dev/dent/v0.0.0/status-check/mod_run.ts http://localhost:5984 http://localhost:7878 http://localhost:8989
    - deno run --allow-env --allow-read --allow-write --unstable https://raw.githubusercontent.com/nativecode-dev/dent/v0.0.0/dent-cli/mod_run.ts refresh --log
    - deno cache --unstable mod.ts
    - deno test --allow-env --allow-net --allow-read --allow-write --unstable
  services:
    - couchdb:2
    - nativecode/test-radarr:latest
    - nativecode/test-sonarr:latest
  variables:
    COUCHDB_USER: admin
    COUCHDB_PASSWORD: password

publish:
  stage: publish
  script:
    - mkdir dist
    - deno bundle mod.ts dist/mod.ts
  only:
    - master
  artifacts:
    paths:
      - dist
