image: nativecode/deno-build:0.1.0

stages:
  - test
  - publish

variables:
  GIT_SUBMODULE_STRATEGY: recursive

.binaries:
  before_script:
    - deno install --allow-net --name status-check https://raw.githubusercontent.com/nativecode-dev/dent/v.0.1.1/status-check/run.ts
    - deno install --allow-run --name dent https://raw.githubusercontent.com/nativecode-dev/dent/dent/v.0.1.1/run.ts
    - echo "export PATH=/root/.deno/bin:$PATH" >> $HOME/.bashrc
    - source $HOME/.bashrc

test:
  extends: .binaries
  stage: test
  script:
    - status-check http://localhost:5984
    - deno run --allow-env --allow-read --allow-write --unstable dent-cli/mod_run.ts refresh --log
    - deno test --allow-env --allow-read --allow-net --allow-write --unstable
  services:
    - couchdb:2
  variables:
    COUCHDB_USER: guest
    COUCHDB_PASSWORD: guest

release:
  extends:
    - .binaries
  stage: publish
  artifacts:
    paths:
      - dist
  script:
    - mkdir dist
    - source .ci-env.sh
    - bash .citools/setup-git ${BUILD_REPO_BRANCH} ${BUILD_REPO_GIT} ${BUILD_REPO_EMAIL}
    - bash .citools/setup-ssh ${BUILD_REPO_DOMAIN} ${BUILD_REPO_SSHKEY_PATH} ${BUILD_REPO_DOMAIN_SSH}
    - deno bundle --unstable mod.ts dist/mod.ts
    - dent tag-release
  only:
    - develop
    - master
