image: nativecode/deno:0.2.0

stages:
  - test
  - publish

test:
  stage: test
  script:
    - deno run --allow-env --allow-read --allow-write http://deno.land/x/gh:nativecode-dev:dent/build.ts
    - deno test --allow-env --allow-net --allow-read --allow-write

publish:
  stage: publish
  script:
    - mkdir dist
    - deno bundle mod.ts dist/mod.ts
  only:
    - master
  artifacts:
    paths:
      - dist
