image: nativecode/deno-build:0.1.0

stages:
  - test
  - publish

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  stage: test
  script:
    - deno run --allow-net https://raw.githubusercontent.com/nativecode-dev/dent/v0.0.0/status-check/mod_run.ts http://localhost:5984 http://localhost:7878 http://localhost:8989
    - deno run --allow-env --allow-read --allow-write --unstable https://raw.githubusercontent.com/nativecode-dev/dent/v0.0.0/dent-cli/mod_run.ts refresh --log
    - deno cache --unstable mod.ts
    - deno test --allow-env --allow-net --allow-read --allow-write --unstable
  services:
    - couchdb:2
    - nativecode/test-radarr:latest
    - nativecode/test-sonarr:latest
  variables:
    COUCHDB_USER: admin
    COUCHDB_PASSWORD: password

prerelease:
  stage: publish
  script:
    - source .ci-env.sh
    - bash .citools/setup-git ${BUILD_REPO_BRANCH} ${BUILD_REPO_GIT} ${BUILD_REPO_EMAIL}
    - bash .citools/setup-ssh ${BUILD_REPO_DOMAIN} ${BUILD_REPO_SSHKEY_PATH} ${BUILD_REPO_DOMAIN_SSH}
    - mkdir dist
    - deno bundle -c tsconfig.json --unstable mod.ts dist/mod.ts
    - npx standard-version --prerelease beta
    - git push --follow-tags origin develop
  only:
    - develop
  artifacts:
    paths:
      - dist

release:
  stage: publish
  script:
    - source .ci-env.sh
    - bash .citools/setup-git ${BUILD_REPO_BRANCH} ${BUILD_REPO_GIT} ${BUILD_REPO_EMAIL}
    - bash .citools/setup-ssh ${BUILD_REPO_DOMAIN} ${BUILD_REPO_SSHKEY_PATH} ${BUILD_REPO_DOMAIN_SSH}
    - mkdir dist
    - deno bundle -c tsconfig.json --unstable mod.ts dist/mod.ts
    - npx standard-version
    - git push --follow-tags origin master
  only:
    - master
  artifacts:
    paths:
      - dist
